services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"     # OTLP/gRPC
      - "16686:16686"     # Jaeger UI
  cassandra:
    image: cassandra:4
    environment:
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 1
      CASSANDRA_START_RPC: 'false'
      JVM_EXTRA_OPTS: -Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.load_ring_state=false -Dcassandra.initial_token=1 -Dcassandra.num_tokens=nil -Dcassandra.allocate_tokens_for_local_replication_factor=nil
    ports:
      - "9042:9042"
  postgres:
    image: postgres:15-alpine
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  kafka:
    image: apache/kafka-native:3.9.0
    ports:
      - "9092:9092"
