addSbtPlugin("com.github.sbt"   % "sbt-github-actions" % "0.24.0")
addSbtPlugin("org.typelevel"    % "sbt-tpolecat"       % "0.5.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"        % "0.6.4")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"       % "2.5.2")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release"     % "1.5.12")
addSbtPlugin("org.scalameta"    % "sbt-mdoc"           % "2.5.4")
