addSbtPlugin("com.github.sbt"            % "sbt-github-actions" % "0.15.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"       % "0.4.2")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"        % "0.6.3")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"       % "2.5.0")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"     % "1.5.12")
