object Versions {
  val caliban                = "2.8.1"
  val catsEffect             = "3.6.1"
  val doobie                 = "1.0.0-RC8"
  val embeddedPostgres       = "2.1.0"
  val fs2                    = "3.12.0"
  val fs2Kafka               = "3.7.0"
  val http4s                 = "0.23.30"
  val kafkaEmbedded          = "3.9.0"
  val logback                = "1.5.18"
  val scribe                 = "3.16.1"
  val skunk                  = "0.6.4"
  val sourceCode             = "0.4.2"
  val sttp                   = "3.11.0"
  val tapir                  = "1.11.24"
  val trace4Cats             = "0.14.7"
  val trace4CatsHttp4sCommon = "0.14.1"
  val trace4CatsGRPCExporter = "0.14.4"
  val virgil                 = "1.2.3"
  val zio                    = "2.1.17"
  val zioHttp                = "3.2.0"
  val zioInteropCats         = "23.1.0.5"
  val zioKafka               = "2.12.0"
  val zioLogging             = "2.5.0"
  val zquery                 = "0.7.5"
}
