object Versions {
  val sourceCode               = "0.4.2"
  val catsEffect               = "3.5.4"
  val fs2                      = "3.10.2"
  val fs2Kafka                 = "3.5.1"
  val trace4Cats               = "0.14.7"
  val trace4CatsJaegarExporter = "0.14.0"
  val trace4CatsHttp4sCommon   = "0.14.1"
  val zio                      = "2.1.1"
  val zioLogging               = "2.3.0"
  val zioInteropCats           = "23.1.0.2"
  val zioHttp                  = "3.0.0-RC7"
  val http4s                   = "0.23.27"
  val tapir                    = "1.10.8"
  val sttp                     = "3.9.5"
  val virgil                   = "1.1.0"
  val doobie                   = "1.0.0-RC5"
  val skunk                    = "0.6.4"
  val embeddedPostgres         = "2.0.7"
  val scribe                   = "3.13.5"
  val zioKafka                 = "2.7.4"
  val kafkaEmbedded            = "3.7.0"
  val logback                  = "1.5.6"
}
