object Versions {
  val caliban                  = "2.8.1"
  val catsEffect               = "3.5.7"
  val doobie                   = "1.0.0-RC5"
  val embeddedPostgres         = "2.1.0"
  val fs2                      = "3.11.0"
  val fs2Kafka                 = "3.6.0"
  val http4s                   = "0.23.30"
  val kafkaEmbedded            = "3.9.0"
  val logback                  = "1.5.12"
  val scribe                   = "3.15.2"
  val skunk                    = "0.6.4"
  val sourceCode               = "0.4.2"
  val sttp                     = "3.10.1"
  val tapir                    = "1.11.10"
  val trace4Cats               = "0.14.7"
  val trace4CatsHttp4sCommon   = "0.14.1"
  val trace4CatsJaegarExporter = "0.14.0"
  val virgil                   = "1.2.2"
  val zio                      = "2.1.13"
  val zioHttp                  = "3.0.1"
  val zioInteropCats           = "23.1.0.3"
  val zioKafka                 = "2.9.0"
  val zioLogging               = "2.4.0"
  val zquery                   = "0.7.5"
}
